### ISSUE TITLE
The get function is logging the url

### ISSUE THREAD

**Issue by fundyc** [fakoua/soxa#9]
In https://deno.land/x/soxa@v1.1/src/core/Soxa.ts in the get function there is a console.log:
    get(url: string, config?: string|Config): Promise<any> {
        console.log(url)
        return this.requestURL(url, 'get', config)
    }
I have seen that in your master branch there is no this console.log. Could you generate a new version, please?

Thanks a lot! You are doing a great work!!

**Comment by fakoua** [comment]
Thank you for reporting this issue, 
I published the version 1.3 with the fix:

https://deno.land/x/soxa@v1.3

v1.2 was ignored by deno.land due to the new changes of the website.

Thank you very much.
